export const apiActionType={
    ADD_API:'ADD_API',
    REMOVE_API:'REMOVE_API',
    UPDATE_API:'UPDATE_API',
    SEARCH_BY_PARAMS:'SEARCH_BY_PARAMS',
    SET_API_LIST:'SET_API_LIST'
}

export const userActionType={
    AUTHENTICATE_USER:'AUTHENTICATE_USER',
    SET_CURRENT_USER:'SET_CURRENT_USER'
}