const API_DATA=[
    {
        id:1001, 
        apiCName: "Aadhar Production BIS API",
        apiName: "Aadhar Production API",
        backendEndPoint: "/test/api",
        backendIP: "27.0.0.1",
        clientId: "username01",
        clientSecret: "kbiorsmbsr563dmfbd",
        consumer: "BIS",
        description: "This is for just testing purpose",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/",
        isActive: "yes",
        port: "443",
        producer: "UIDAI",
        registeredBy: "User01",
        state: "None",
        urlReWritingWith: "uat"
     },
    {
        id:1002,
        apiCName: "Testing A API",
        apiName: "Testing A Consumer1 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer1",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/a/con1",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1003,
        apiCName: "Testing A API",
        apiName: "Testing A Consumer2 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer2",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/a/con2",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1004,
        apiCName: "Testing A API",
        apiName: "Testing A Consumer3 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer3",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/a/con3",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1005,
        apiCName: "Testing B API",
        apiName: "Testing B Consumer1 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer1",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/b/con1",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1006,
        apiCName: "Testing B API",
        apiName: "Testing B Consumer2 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer2",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/b/con2",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1007,
        apiCName: "Testing B API",
        apiName: "Testing B Consumer3 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer3",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/b/con3",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1008,
        apiCName: "A API",
        apiName: "A Consumer4 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer4",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/api/a/con4",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1009,
        apiCName: "A API",
        apiName: "A Consumer5 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer5",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/api/a/con5",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    },
    {
        id:1010,
        apiCName: "B API",
        apiName: "B Consumer5 API",
        backendEndPoint: "/test/api",
        backendIP: "localhost",
        clientId: "username02",
        clientSecret: "cngbsrbfimtoimb3",
        consumer: "Consumer5",
        description: "this is testing box",
        fullBackendUrl: "",
        gatewayUrl: "https://gatewayDomain/api/b/con5",
        isActive: "yes",
        port: "443",
        producer: "Producer",
        registeredBy: "DJ",
        state: "Delhi",
        urlReWritingWith: "test"
    }

 ]
 
 export default API_DATA;